#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
sudo touch /var/www/html/index.html
echo "Hello World!"  | sudo tee /var/www/html/index.html
service nginx start 
