#!/usr/bin/env bash
# Not found page 404

sudo apt-get update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default
service nginx restart
