#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

hour=0
min=1
while [ $hour -le 12 ];
do
	echo "Hour: $hour"
	while [ $min -ne 60 ];
	do
		echo $min
	((min++))
	done
	((hour++))
	min=1
done
